### PR TITLE
fix typos in Changes

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by karenetheridge** [comment]
...?  :(

**Comment by DarwinAwardWinner** [comment]
Whoops, some bad timing. I had a trial release ready to go from a few days ago, and your post on RT reminded me to release it for real. And then I checked my email and saw this.

**Comment by DarwinAwardWinner** [comment]
FWIW, I marked it as v7-compatible because the warnings say that v7 is when support for the old way will be dropped.

**Comment by DarwinAwardWinner** [comment]
Should I just increment the version number and cut another release?

**Comment by karenetheridge** [comment]
Ah, ok, I thought the v7 was a typo and intended to be v6. I guess you could reference either version in there.

**Pull request merged**
