### PR TITLE
use List::Util instead of List::AllUtils+List::MoreUtils

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by karenetheridge** [comment]
\o/

**Comment by DarwinAwardWinner** [comment]
I'll make a release soonish. I'm not at a machine that I can release from right now.

**Comment by karenetheridge** [comment]
Hi, would it be possible to release this? I expect it has been forgotten about. :)  thanks!

**Comment by DarwinAwardWinner** [comment]
Um, yes, looks like I lost track of this. I'll do a release from home tonight.

**Comment by karenetheridge** [comment]
Hi, would it be possible to release this? I expect it has been forgotten about. :)  thanks!

**Comment by karenetheridge** [comment]
(oops sorry doublepaste)

**Comment by DarwinAwardWinner** [comment]
Hmm, there's a release v0.151680 tagged from 8 months ago: https://github.com/DarwinAwardWinner/Dist-Zilla-Plugin-CopyFilesFromBuild/commit/4cec4bdc3fe672578321da529f776d5d172c89b2

And it matches the version I see on metacpan: https://metacpan.org/pod/Dist::Zilla::Plugin::CopyFilesFromBuild

**Comment by karenetheridge** [comment]
DOH

:D

**Pull request merged**
